# Generated by Django 5.2.1 on 2025-06-08 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HospiApp', '0004_mensaje_leido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensaje',
            old_name='receptor',
            new_name='receptor',
        ),
    ]
